### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by unaiic**
This patch formats the code following C++ Style Guide (from Google). Improves readability and makes the code look cleaner.

### CODE REVIEW

**Comment by unaiic** [comment]
Some changes might not be good, as I did the formatting automatically; so there may be some ugly chess-specific code now...

**Comment by connormcmonigle** [comment]
Hmm. I actually find the automatically formatted code far less readable. However, I do agree that I should probably be consistent with my formatting and finding an au. Was there any particularly egregious formatting that prompted you to open this PR?

Thanks for your interest in my project.

**Comment by unaiic** [comment]
I agree that some formatting depends on personal taste, but yeah, maybe inconsistency and lack of spaces next to curly braces etc. is what makes me harder to read the code. I was looking at it as I'm really interested and like your approach. I think your ideas are very good and I was trying to deepen my understanding of the source code. I've been contributing to the Stockfish project and I think this one is a good one to keep an eye on too. May I ask you what tests do you do to ensure the elo gain of a patch? Or what format do you use for nn training, something similar to SF's .plain?

Thank you for answering btw.

**Comment by connormcmonigle** [comment]
I'll do some experimentation with clang-format and see if there's a style I like. Personally, I'm not a huge fan of Google's style guide so I'll probably close this PR if that's alright with you.

The training data format consists of just text files at the moment. Every line contains a fen and a WDL probabilities corresponding to the network's estimate of the position resulting from a playout to a lower piece count position. The WDL probabilities are scaled by 1024 and cast to integers to make parsing faster. Long term, I might switch to a more compact representation (hence why 1024, enabling the probabilities to be packed into a 32 bit integer).

Here's a link to a slightly older version of my training data:
[https://drive.google.com/file/d/1vcdyjUEXwbOtBrZDItMVPRTN0axznhRI/view?usp=sharing](url)

**Comment by unaiic** [comment]
> I'll probably close this PR if that's alright with you.

Ok, no problem.

> Every line contains a fen and a WDL probabilities corresponding to the network's estimate of the position resulting from a playout to a lower piece count position.

Do you first trained the net on TB data and then retrained it on data with >6 pieces, or all in one run but starting from <=6 piece data? I mean, some kind of RL or everything at once.

Thank you again.

**Comment by connormcmonigle** [comment]
Your question is not entirely clear to me, sorry. Hopefully the below answers your question.

The first generation network is trained on <=6 man positions labelled utilizing syzygy EGTBs. The first generation network is then used in conjunction with Seer's search to playout all the 7 man positions to <=6 man positions. As the first generation network learned to evaluate the <=6 man positions very accurately as it was provided perfect labels, we can obtain reasonable labels for the 7 man positions using the network's static WDL prediction of the resultant positions after the playouts.

The second generation network is then trained on all the <=7 man labelled positions. We can then use the second generation network to obtain labels for the 8 man positions using the same process we used to label the 7 man positions using the first generation network. 

We then repeat this process until all the positions are labelled. At each step, we're effectively projecting the unknown samples into a known domain (via the playout) and growing the known in discrete steps.

**Comment by unaiic** [comment]
Thanks, it answers the question really well. IIRC you used random positions from lichess games, right? If so, does the source of the data (being positions taken from human games) affect the training of the net (with your approach), or are only the diversity of the positions the key here?

**Comment by connormcmonigle** [comment]
My hunch is that diversity is most important. I did some experiments with filtering the games based on elo and the difference wasn't particularly dramatic. Using only human games where one of the two players was >1900 Lichess elo might have been worth about 20 elo. However, I also had introduced some other changes so it's not immediately clear, especially as the run to run variance in performance is unknown.

The other advantage of filtering was that sub 1900 players often play into stupid positions which occasionally caused my search to blow up. This resulted in generating playout sometimes taking a ridiculous amount of time.

**Pull request closed without merging**
